package org.bian.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.bian.dto.CRSuitabilityAssessmentEvaluateInputModelSuitabilityAssessmentInstanceRecordProposedMarketOrderTransaction;

import javax.validation.Valid;
  
/**
 * CRSuitabilityAssessmentEvaluateOutputModelSuitabilityAssessmentInstanceRecord
 */
public class CRSuitabilityAssessmentEvaluateOutputModelSuitabilityAssessmentInstanceRecord   {
  private CRSuitabilityAssessmentEvaluateInputModelSuitabilityAssessmentInstanceRecordProposedMarketOrderTransaction proposedMarketOrderTransaction = null;

  private String suitabilityAssessmentType = null;

  private String documentDirectoryEntryInstanceReference = null;

  private String correspondenceInstanceReference = null;

  private String suitabilityComplianceAssessmentWorkProducts = null;

  private String suitabilityComplianceAssessmentResult = null;


  /**
   * Get proposedMarketOrderTransaction
   * @return proposedMarketOrderTransaction
  **/

  public CRSuitabilityAssessmentEvaluateInputModelSuitabilityAssessmentInstanceRecordProposedMarketOrderTransaction getProposedMarketOrderTransaction() {
    return proposedMarketOrderTransaction;
  }

  public void setProposedMarketOrderTransaction(CRSuitabilityAssessmentEvaluateInputModelSuitabilityAssessmentInstanceRecordProposedMarketOrderTransaction proposedMarketOrderTransaction) {
    this.proposedMarketOrderTransaction = proposedMarketOrderTransaction;
  }


  /**
   * `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The type and make-up of suitability compliance tests referenced in the assessment 
   * @return suitabilityAssessmentType
  **/

  public String getSuitabilityAssessmentType() {
    return suitabilityAssessmentType;
  }

  public void setSuitabilityAssessmentType(String suitabilityAssessmentType) {
    this.suitabilityAssessmentType = suitabilityAssessmentType;
  }


  /**
   * `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: The document reference for any documents accessed and generated (e.g. disclosures) 
   * @return documentDirectoryEntryInstanceReference
  **/

  public String getDocumentDirectoryEntryInstanceReference() {
    return documentDirectoryEntryInstanceReference;
  }

  public void setDocumentDirectoryEntryInstanceReference(String documentDirectoryEntryInstanceReference) {
    this.documentDirectoryEntryInstanceReference = documentDirectoryEntryInstanceReference;
  }


  /**
   * `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to any correspondence generated by the suitability check 
   * @return correspondenceInstanceReference
  **/

  public String getCorrespondenceInstanceReference() {
    return correspondenceInstanceReference;
  }

  public void setCorrespondenceInstanceReference(String correspondenceInstanceReference) {
    this.correspondenceInstanceReference = correspondenceInstanceReference;
  }


  /**
   * `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Work documentation, forms and schedules produced and referenced during the assessment 
   * @return suitabilityComplianceAssessmentWorkProducts
  **/

  public String getSuitabilityComplianceAssessmentWorkProducts() {
    return suitabilityComplianceAssessmentWorkProducts;
  }

  public void setSuitabilityComplianceAssessmentWorkProducts(String suitabilityComplianceAssessmentWorkProducts) {
    this.suitabilityComplianceAssessmentWorkProducts = suitabilityComplianceAssessmentWorkProducts;
  }


  /**
   * `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Outcome/result of the suitability assessment, can include reported details if appropriate 
   * @return suitabilityComplianceAssessmentResult
  **/

  public String getSuitabilityComplianceAssessmentResult() {
    return suitabilityComplianceAssessmentResult;
  }

  public void setSuitabilityComplianceAssessmentResult(String suitabilityComplianceAssessmentResult) {
    this.suitabilityComplianceAssessmentResult = suitabilityComplianceAssessmentResult;
  }


}

